# Variant-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=rhel
NAME=rhcos
STREAM=rhel-9.8
DESCRIPTION=Red Hat Enterprise Linux CoreOS 9.8
VERSION=9.8
MUTATE_OS_RELEASE=9.8
BUILDER_IMG=registry.stage.redhat.io/rhel9/rhel-bootc:9.8@sha256:62da51aec3bb7c4f90d660c2b8b250a0722a2b4f7142f4a73cde26c62cc4dc23
MANIFEST=manifest-rhel-9.8.yaml
IMAGE_CONFIG=image-rhel-9.8.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=.
INJECT_OPENSHIFT_VERSION_LABELS=1
