# Variant-specific build arguments.
# Pass to buildah/podman using `--build-arg-file`.

ID=rhel
NAME=rhcos
STREAM=rhel-10.2
DESCRIPTION=Red Hat Enterprise Linux CoreOS 10.2
VERSION=10.2
MUTATE_OS_RELEASE=10.2
BUILDER_IMG=registry.stage.redhat.io/rhel10/rhel-bootc:10.2@sha256:21f865f8fa3c0af07b41fddbf0e1626c40b1a22248d3a4ce1452c32df282c2c9
MANIFEST=manifest-rhel-10.2.yaml
IMAGE_CONFIG=image-rhel-10.2.yaml
# XXX: see inject_passwd_group() in build-rootfs
PASSWD_GROUP_DIR=.
INJECT_OPENSHIFT_VERSION_LABELS=1
